apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dapr-system

helmCharts:
- name: dapr
  namespace: dapr-system
  includeCRDs: true
  releaseName: dapr
  version: 1.15.0
  repo: https://dapr.github.io/helm-charts
  valuesFile: values.yaml

